name: 'ftp-clean-directory-action'
author: 'Alexandre CHAUDET <alexandre@rockett.fr>'
description: 'Automate deleting all the contents of a directory via FTP using this GitHub action.'
inputs:
  host:
    description: 'FTP host'
    required: true
  user:
    description: 'FTP user'
    required: true
  password:
    description: 'FTP password'
    required: true
  workingDir:
    description: 'Working directory'
    required: false
    default: '/'
  ignoreSSL:
    description: 'Ignore invalid TLS/SSL certificate (1=ignoreSSL)'
    required: false
    default: '0'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  color: 'orange'
  icon: 'delete'
